#!/bin/sh
#
#  Installs my Bash environment and other configurations into $HOME directory.
#
#    - bash (startup files)
#    - ~/bin scripts for various scipting languages
#    - ssh, bloop (Scala), Cabal (Haskell)
#    - create directories important to my work flow
#    - remove items
#

repoName=home
export scriptName=homeInstall

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
HOME_GIT_REPO="${HOME_GIT_REPO:=$HOME/devel/home}"
umask 0022

cd "$HOME_GIT_REPO" || {
   printf '\nError - failed to cd into "%s"\n' "$scriptName" "$HOME_GIT_REPO"
   return 1
}

## Source install infrastructure if necessary
. ./installSource.sh

HOME_FILES='
   .bash_profile
   .bashrc
   .inputrc
'

BIN_SCRIPTS='
   buArch
   chkcolor
   codepoint
   digpath
   monitor
   myCalc
   pathtrim
   rt
   spin
   startw
   viewJarManifest
'

SSH_FILES='
   config
'

BLOOP_FILES='
   bloop.json
'

CABAL_FILES='
   config
'

RM_TARGET_ITEMS="
   $HOME/.vimrc
"

DIRS_TO_CREATE="
   $HOME/catch
   $HOME/.local/bin
   $HOME/.cabal/bin
"

## Install or Check

# Install bash config files
install_files "$HOME" "$HOME_FILES" . 0644 "$switch"

# Install ~/bin scripts
install_files "$HOME/bin" "$BIN_SCRIPTS" ./bin 0755 "$switch"
chmod 0755 "$HOME/bin"

# Install SSH Configs
install_files "$HOME/.ssh" "$SSH_FILES" ./ssh 0600 "$switch"
chmod 0700 "$HOME/.ssh"

# Install Bloop Configs for Scala
install_files "$HOME/.bloop" "$BLOOP_FILES" ./bloop 0644 "$switch"
chmod 0755 "$HOME/.bloop"

# Install Cabal Configs for Haskell
install_files "$HOME/.cabal" "$CABAL_FILES" ./cabal 0644 "$switch"
chmod 0755 "$HOME/.cabal"

# Remove/report no longer needed files and directories
remove_items "$RM_TARGET_ITEMS"

# Create/report missing directories
ensure_dirs "$DIRS_TO_CREATE"

## Adjustments/tweaks/tasks
case "$switch" in
   install)
      :
      ;;
   repo)
      # Get git status info on repo
      printf '\nGit Status:\n'
      git status -s
      ;;
   target)
      :
      ;;
esac
